#docker-compose

version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      -postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bd_spondere
    
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python main.py'
    volumes:
      - .:/spondereServer
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/bd_spondere
    depends_on:
      - db


volumes:
  postgres_data: