insert into group_students 
	(studentusername, groupid)
values
	--2021
	('silvio', 1),
	('wander', 1),
	('james', 1),
	('antonio', 1),
	('jessica', 2),
	('wander', 2),
	('ruth', 2),
	('maria', 2),
	--2022
	('silvio', 3),
	('james', 3),
	('flavia', 3),
	('orlando', 3),
	('silvio', 4),
	('wander', 4),
	('james', 4),
	('antonio', 4),
	('flavia', 4),
	('orlando', 4),
	('Amirani', 4),
	('kelleigh', 4),
	('tyrrell', 4),
	('ruth', 4),
	('jessica', 4),
	('almir', 4),
	('maria', 5),
	('flavia', 5),
	('kelleigh', 6),
	('maria', 6),
	('kelleigh', 7),
	('tristram', 7),
	('almir', 7),
	('jessica', 7);
